### PR TITLE
[LOC]Back-Translation "Visual Studio コード"→"Visual Studio Code"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/ja-jp/power-automate/create-adaptive-cards

### CODE REVIEW

**Comment by hyoshioka0128** [comment]
@TinaMcN Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by TinaMcN** [comment]
@SonjaSaltzman do you know who owns the localization of this content?

**Comment by SonjaSaltzman** [comment]
should be @vinceno

**Comment by vinceno** [comment]
thx., and on to @jowilco

**Comment by jowilco** [comment]
@hyoshioka0128 フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
Translation changes have been implemented as part of the regular translation process. Thank you for bringing the issue to our attention.

**Pull request closed without merging**
